export interface EquipmentSpec {
  id: string;
  name: string;
  manufacturer: string;
  category: "Lighting" | "Audio" | "Video" | "Rigging" | "Staging" | "Other";
  subcategory: string;
  powerRating: number;
  voltage: number;
  powerFactor: number;
  inrushType: "LED" | "Incandescent" | "Motor" | "Transformer" | "Capacitive";
  connector: string;
  notes?: string;
}

export const EQUIPMENT_LIBRARY: EquipmentSpec[] = [
  {
    id: "led-par-chauvet-colorstrike",
    name: "COLORstrike M",
    manufacturer: "Chauvet",
    category: "Lighting",
    subcategory: "LED PAR",
    powerRating: 187,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "LED",
    connector: "Edison",
  },
  {
    id: "led-par-elation-sixpar-300",
    name: "SIXPAR 300",
    manufacturer: "Elation",
    category: "Lighting",
    subcategory: "LED PAR",
    powerRating: 300,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "LED",
    connector: "Powercon",
  },
  {
    id: "led-par-martin-rush-par2-rgbw",
    name: "Rush PAR 2 RGBW",
    manufacturer: "Martin",
    category: "Lighting",
    subcategory: "LED PAR",
    powerRating: 210,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "LED",
    connector: "Powercon",
  },
  {
    id: "moving-head-clay-paky-sharpy",
    name: "Sharpy",
    manufacturer: "Clay Paky",
    category: "Lighting",
    subcategory: "Moving Head",
    powerRating: 270,
    voltage: 120,
    powerFactor: 0.90,
    inrushType: "Transformer",
    connector: "Powercon",
  },
  {
    id: "moving-head-martin-mac-aura",
    name: "MAC Aura",
    manufacturer: "Martin",
    category: "Lighting",
    subcategory: "Moving Head",
    powerRating: 250,
    voltage: 120,
    powerFactor: 0.92,
    inrushType: "LED",
    connector: "Powercon",
  },
  {
    id: "moving-head-robe-robin-600",
    name: "Robin 600 LED Wash",
    manufacturer: "Robe",
    category: "Lighting",
    subcategory: "Moving Head",
    powerRating: 580,
    voltage: 120,
    powerFactor: 0.92,
    inrushType: "LED",
    connector: "Powercon",
  },
  {
    id: "par-can-64-1000w",
    name: "PAR 64 1000W",
    manufacturer: "Generic",
    category: "Lighting",
    subcategory: "PAR Can",
    powerRating: 1000,
    voltage: 120,
    powerFactor: 1.0,
    inrushType: "Incandescent",
    connector: "Edison",
  },
  {
    id: "par-can-56-300w",
    name: "PAR 56 300W",
    manufacturer: "Generic",
    category: "Lighting",
    subcategory: "PAR Can",
    powerRating: 300,
    voltage: 120,
    powerFactor: 1.0,
    inrushType: "Incandescent",
    connector: "Edison",
  },
  {
    id: "leko-source-four-750w",
    name: "Source Four 750W",
    manufacturer: "ETC",
    category: "Lighting",
    subcategory: "Ellipsoidal",
    powerRating: 750,
    voltage: 120,
    powerFactor: 1.0,
    inrushType: "Incandescent",
    connector: "Stage Pin",
  },
  {
    id: "led-blinder-chauvet-strike",
    name: "Strike 4",
    manufacturer: "Chauvet",
    category: "Lighting",
    subcategory: "LED Blinder",
    powerRating: 400,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "LED",
    connector: "Powercon",
  },
  {
    id: "haze-machine-martin-jem-k1",
    name: "JEM K1 Hazer",
    manufacturer: "Martin",
    category: "Lighting",
    subcategory: "Effects",
    powerRating: 290,
    voltage: 120,
    powerFactor: 0.85,
    inrushType: "Motor",
    connector: "Edison",
  },
  {
    id: "dimmer-etc-sensor3-12ch",
    name: "Sensor3 12-Channel",
    manufacturer: "ETC",
    category: "Lighting",
    subcategory: "Dimmer",
    powerRating: 100,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "Capacitive",
    connector: "Hardwired",
    notes: "Control only, load calculated separately",
  },
  {
    id: "amp-crown-xti-6002",
    name: "XTi 6002",
    manufacturer: "Crown",
    category: "Audio",
    subcategory: "Power Amplifier",
    powerRating: 2800,
    voltage: 120,
    powerFactor: 0.88,
    inrushType: "Capacitive",
    connector: "Powercon",
  },
  {
    id: "amp-qsc-plx-3602",
    name: "PLX 3602",
    manufacturer: "QSC",
    category: "Audio",
    subcategory: "Power Amplifier",
    powerRating: 2100,
    voltage: 120,
    powerFactor: 0.90,
    inrushType: "Capacitive",
    connector: "Edison",
  },
  {
    id: "amp-yamaha-px8",
    name: "PX8",
    manufacturer: "Yamaha",
    category: "Audio",
    subcategory: "Power Amplifier",
    powerRating: 2800,
    voltage: 120,
    powerFactor: 0.87,
    inrushType: "Capacitive",
    connector: "Powercon",
  },
  {
    id: "console-yamaha-cl5",
    name: "CL5 Digital Console",
    manufacturer: "Yamaha",
    category: "Audio",
    subcategory: "Mixing Console",
    powerRating: 75,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "Capacitive",
    connector: "IEC C13",
  },
  {
    id: "console-digico-sd12",
    name: "SD12 Console",
    manufacturer: "DiGiCo",
    category: "Audio",
    subcategory: "Mixing Console",
    powerRating: 100,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "Capacitive",
    connector: "IEC C13",
  },
  {
    id: "console-allen-heath-sq7",
    name: "SQ-7 Console",
    manufacturer: "Allen & Heath",
    category: "Audio",
    subcategory: "Mixing Console",
    powerRating: 60,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "Capacitive",
    connector: "IEC C13",
  },
  {
    id: "speaker-jbl-srx835p",
    name: "SRX835P Powered Speaker",
    manufacturer: "JBL",
    category: "Audio",
    subcategory: "Powered Speaker",
    powerRating: 2000,
    voltage: 120,
    powerFactor: 0.88,
    inrushType: "Capacitive",
    connector: "Powercon",
  },
  {
    id: "speaker-qsc-k12-2",
    name: "K12.2 Powered Speaker",
    manufacturer: "QSC",
    category: "Audio",
    subcategory: "Powered Speaker",
    powerRating: 2000,
    voltage: 120,
    powerFactor: 0.90,
    inrushType: "Capacitive",
    connector: "Powercon",
  },
  {
    id: "subwoofer-jbl-srx828sp",
    name: "SRX828SP Subwoofer",
    manufacturer: "JBL",
    category: "Audio",
    subcategory: "Powered Subwoofer",
    powerRating: 2000,
    voltage: 120,
    powerFactor: 0.88,
    inrushType: "Capacitive",
    connector: "Powercon",
  },
  {
    id: "monitor-qsc-k10-2",
    name: "K10.2 Monitor",
    manufacturer: "QSC",
    category: "Audio",
    subcategory: "Stage Monitor",
    powerRating: 2000,
    voltage: 120,
    powerFactor: 0.90,
    inrushType: "Capacitive",
    connector: "Powercon",
  },
  {
    id: "projector-panasonic-pt-rz12ku",
    name: "PT-RZ12KU Projector",
    manufacturer: "Panasonic",
    category: "Video",
    subcategory: "Projector",
    powerRating: 1380,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "Transformer",
    connector: "Edison",
  },
  {
    id: "projector-barco-rlm-w8",
    name: "RLM-W8 Projector",
    manufacturer: "Barco",
    category: "Video",
    subcategory: "Projector",
    powerRating: 1900,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "Transformer",
    connector: "IEC C19",
  },
  {
    id: "led-wall-roi-e18",
    name: "E18 LED Panel",
    manufacturer: "ROE Visual",
    category: "Video",
    subcategory: "LED Wall",
    powerRating: 400,
    voltage: 120,
    powerFactor: 0.92,
    inrushType: "LED",
    connector: "Powercon",
    notes: "Per panel, avg 40% brightness",
  },
  {
    id: "led-processor-brompton-sx40",
    name: "SX40 LED Processor",
    manufacturer: "Brompton",
    category: "Video",
    subcategory: "Video Processor",
    powerRating: 100,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "Capacitive",
    connector: "IEC C13",
  },
  {
    id: "video-switcher-blackmagic-atem-2",
    name: "ATEM 2 M/E Switcher",
    manufacturer: "Blackmagic",
    category: "Video",
    subcategory: "Video Switcher",
    powerRating: 100,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "Capacitive",
    connector: "IEC C13",
  },
  {
    id: "camera-sony-pxw-z280",
    name: "PXW-Z280 Camera",
    manufacturer: "Sony",
    category: "Video",
    subcategory: "Camera",
    powerRating: 23,
    voltage: 12,
    powerFactor: 1.0,
    inrushType: "Capacitive",
    connector: "DC",
    notes: "Via battery or AC adapter",
  },
  {
    id: "hoist-cm-lodestar-1ton",
    name: "Lodestar 1-Ton Hoist",
    manufacturer: "CM",
    category: "Rigging",
    subcategory: "Chain Hoist",
    powerRating: 1800,
    voltage: 120,
    powerFactor: 0.75,
    inrushType: "Motor",
    connector: "Stage Pin",
  },
  {
    id: "hoist-prodigy-half-ton",
    name: "Prodigy 1/2-Ton Hoist",
    manufacturer: "CM",
    category: "Rigging",
    subcategory: "Chain Hoist",
    powerRating: 900,
    voltage: 120,
    powerFactor: 0.75,
    inrushType: "Motor",
    connector: "Edison",
  },
  {
    id: "laptop-macbook-pro-16",
    name: "MacBook Pro 16-inch",
    manufacturer: "Apple",
    category: "Other",
    subcategory: "Computer",
    powerRating: 140,
    voltage: 120,
    powerFactor: 0.98,
    inrushType: "Capacitive",
    connector: "IEC C5",
  },
  {
    id: "router-ubiquiti-dream-machine",
    name: "UniFi Dream Machine Pro",
    manufacturer: "Ubiquiti",
    category: "Other",
    subcategory: "Network",
    powerRating: 37,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "Capacitive",
    connector: "IEC C13",
  },
  {
    id: "switch-netgear-m4300-48x",
    name: "M4300-48X Switch",
    manufacturer: "Netgear",
    category: "Other",
    subcategory: "Network",
    powerRating: 90,
    voltage: 120,
    powerFactor: 0.95,
    inrushType: "Capacitive",
    connector: "IEC C13",
  },
];

export function searchEquipment(query: string): EquipmentSpec[] {
  const lowercaseQuery = query.toLowerCase();
  return EQUIPMENT_LIBRARY.filter(
    (eq) =>
      eq.name.toLowerCase().includes(lowercaseQuery) ||
      eq.manufacturer.toLowerCase().includes(lowercaseQuery) ||
      eq.category.toLowerCase().includes(lowercaseQuery) ||
      eq.subcategory.toLowerCase().includes(lowercaseQuery)
  );
}

export function getEquipmentByCategory(
  category: EquipmentSpec["category"]
): EquipmentSpec[] {
  return EQUIPMENT_LIBRARY.filter((eq) => eq.category === category);
}

export function getEquipmentById(id: string): EquipmentSpec | undefined {
  return EQUIPMENT_LIBRARY.find((eq) => eq.id === id);
}

export const EQUIPMENT_CATEGORIES: EquipmentSpec["category"][] = [
  "Lighting",
  "Audio",
  "Video",
  "Rigging",
  "Staging",
  "Other",
];
